

export const API_WIDGET_GUEST_LIST = 'API_WIDGET_GUEST_LIST';

export const API_WIDGET_DATA_LIST = 'API_WIDGET_DATA_LIST';

export const API_WIDGET_FOLLOW_GUEST = 'API_WIDGET_FOLLOW_GUEST';

export const API_WIDGET_UNFOLLOW_GUEST = 'API_WIDGET_UNFOLLOW_GUEST';

export const SWITCH_AWARD_WIDGET = 'SWITCH_AWARD_WIDGET';
