

// 更新订阅数量、标题、logo
export const UPDATE_STAR_INFO = 'UPDATE_STAR_INFO';

// 更新订阅数量
export const UPDATE_SUBSCRIBE_COUNT = 'UPDATE_SUBSCRIBE_COUNT';

// 更新订阅状态
export const UPDATE_SUBSCRIBE_TYPE = 'UPDATE_SUBSCRIBE_TYPE';

// 订阅
export const UPDATE_SUBSCRIBE_STATUS_SUBSCRIBE = 'UPDATE_SUBSCRIBE_STATUS_SUBSCRIBE';

// 取消订阅
export const UPDATE_SUBSCRIBE_STATUS_UNSUBSCRIBE = 'UPDATE_SUBSCRIBE_STATUS_UNSUBSCRIBE';

// 更新在线人数
export const UPDATE_VIEWER_COUNT = 'UPDATE_VIEWER_COUNT';

// 清除订阅提示
export const CLEAR_SUBSCRIBE_TIPS = 'CLEAR_SUBSCRIBE_TIPS';
