
export const API_PKBLOOD_GUEST_LIST = 'API_PKBLOOD_GUEST_LIST';

export const API_PKBLOOD_GROUP_LIST = 'API_PKBLOOD_GROUP_LIST';

export const API_PKBLOOD_PENDANT = 'API_PKBLOOD_PENDANT';

export const SWITCH_PKBLOOD_COMPT = 'SWITCH_PKBLOOD_COMPT';

export const SHOW_PKBLOOD_RANK = 'SHOW_PKBLOOD_RANK';

export const HIDE_PKBLOOD_RANK = 'HIDE_PKBLOOD_RANK';

export const SWITCH_FOLD_BTN = 'SWITCH_FOLD_BTN';

export const SWITCH_BLOOD_BAR = 'SWITCH_BLOOD_BAR';

export const SLIDE_BLOOD_BAR = 'SLIDE_BLOOD_BAR';

export const UPDATA_BLOOD_SOCKET_DATA = 'UPDATA_BLOOD_SOCKET_DATA';

export const UPDATE_PK_GROUP_LIST = 'UPDATE_PK_GROUP_LIST';
